version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  backend1:
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - rabbitmq

  backend2:
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - postgres
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - 9999:9999
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgres
      - rabbitmq